"use client";
import {useEffect,useMemo,useState} from "react";
import {WalletMultiButton} from "@solana/wallet-adapter-react-ui";
import {useConnection,useWallet} from "@solana/wallet-adapter-react";
import {PublicKey,Transaction} from "@solana/web3.js";
import {createAssociatedTokenAccountInstruction,getAssociatedTokenAddressSync,createTransferInstruction,getAccount} from "@solana/spl-token";
import {ArrowDownUp,Droplets,ExternalLink,RefreshCw,ShieldCheck} from "lucide-react";
import {initializeIx,poolPda,quote,swapIx} from "@/lib/amm";

type Mode="swap"|"pool"; const explorer=(s:string)=>`https://explorer.solana.com/tx/${s}?cluster=devnet`;
export default function Home(){const {connection}=useConnection();const wallet=useWallet();const [mode,setMode]=useState<Mode>("swap");const [mintA,setMintA]=useState("");const [mintB,setMintB]=useState("");const [amount,setAmount]=useState("");const [second,setSecond]=useState("");const [fee,setFee]=useState("30");const [slippage,setSlippage]=useState("0.5");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);const pool=useMemo(()=>wallet.publicKey?poolPda(wallet.publicKey):null,[wallet.publicKey]);
const submit=async()=>{if(!wallet.publicKey||!wallet.sendTransaction) return setStatus("请先连接钱包");setBusy(true);setStatus("正在校验并模拟交易…");try{const a=new PublicKey(mintA),b=new PublicKey(mintB);if(a.equals(b))throw new Error("两种代币 mint 必须不同");const p=poolPda(wallet.publicKey);const va=getAssociatedTokenAddressSync(a,p,true),vb=getAssociatedTokenAddressSync(b,p,true);const ua=getAssociatedTokenAddressSync(a,wallet.publicKey),ub=getAssociatedTokenAddressSync(b,wallet.publicKey);const tx=new Transaction();if(mode==="pool"){if(await connection.getAccountInfo(p))throw new Error("该钱包已初始化过池");if(!await connection.getAccountInfo(va))tx.add(createAssociatedTokenAccountInstruction(wallet.publicKey,va,p,a));if(!await connection.getAccountInfo(vb))tx.add(createAssociatedTokenAccountInstruction(wallet.publicKey,vb,p,b));tx.add(initializeIx(wallet.publicKey,va,vb,Number(fee)));tx.add(createTransferInstruction(ua,va,wallet.publicKey,BigInt(amount)));tx.add(createTransferInstruction(ub,vb,wallet.publicKey,BigInt(second)));}else{const ra=(await getAccount(connection,va)).amount,rb=(await getAccount(connection,vb)).amount;const input=BigInt(amount);const out=quote(input,ra,rb,Number(fee));const min=out*BigInt(Math.floor((100-Number(slippage))*100))/10000n;tx.add(swapIx(wallet.publicKey,p,ua,ub,va,vb,input,min));}
const latest=await connection.getLatestBlockhash();tx.feePayer=wallet.publicKey;tx.recentBlockhash=latest.blockhash;const sim=await connection.simulateTransaction(tx);if(sim.value.err)throw new Error(`模拟失败: ${JSON.stringify(sim.value.err)}`);setStatus("模拟成功，等待钱包签名…");const sig=await wallet.sendTransaction(tx,connection);await connection.confirmTransaction({...latest,signature:sig},"confirmed");setStatus(`SUCCESS:${sig}`);}catch(e){setStatus(e instanceof Error?e.message:"交易失败");}finally{setBusy(false)}};
useEffect(()=>{setStatus("")},[mode]);return <main><header><a className="brand" href="#" aria-label="K-Swap 首页"><span>K</span>SWAP</a><div className="network"><i/>DEVNET</div><WalletMultiButton/></header><section className="hero"><div><p className="eyebrow">PINOCCHIO-POWERED AMM</p><h1>交换资产，<br/><em>保持掌控。</em></h1><p className="lead">直接从钱包创建恒定乘积流动池，或在 Solana devnet 上以原子交易完成 SPL Token 交换。</p><div className="trust"><span><ShieldCheck/>链上校验</span><span><RefreshCw/>实时储备</span><span><Droplets/>x · y = k</span></div></div><div className="trade-card"><nav aria-label="交易模式"><button className={mode==="swap"?"active":""} onClick={()=>setMode("swap")}>Swap</button><button className={mode==="pool"?"active":""} onClick={()=>setMode("pool")}>创建池</button></nav><label>Token A mint<input value={mintA} onChange={e=>setMintA(e.target.value.trim())} placeholder="Solana mint 地址"/></label><div className="amount"><label>{mode==="pool"?"A 初始数量（最小单位）":"输入数量（最小单位）"}<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value.replace(/\D/g,""))} placeholder="0"/></label></div><button className="flip" aria-label="交换代币方向" disabled={mode==="pool"} onClick={()=>{setMintA(mintB);setMintB(mintA)}}><ArrowDownUp/></button><label>Token B mint<input value={mintB} onChange={e=>setMintB(e.target.value.trim())} placeholder="Solana mint 地址"/></label>{mode==="pool"?<><label>B 初始数量（最小单位）<input inputMode="numeric" value={second} onChange={e=>setSecond(e.target.value.replace(/\D/g,""))} placeholder="0"/></label><label>手续费（bps，最高 1000）<input inputMode="numeric" value={fee} onChange={e=>setFee(e.target.value.replace(/\D/g,""))}/></label></>:<label>滑点容忍度（%）<input inputMode="decimal" value={slippage} onChange={e=>setSlippage(e.target.value)}/></label>}<div className="details"><span>Pool PDA</span><code>{pool?`${pool.toBase58().slice(0,8)}…${pool.toBase58().slice(-6)}`:"连接钱包后推导"}</code></div><button className="submit" disabled={busy||!wallet.connected||!mintA||!mintB||!amount||(mode==="pool"&&!second)} onClick={submit}>{busy?"处理中…":!wallet.connected?"请先连接钱包":mode==="pool"?"创建并注入流动性":"预检并交换"}</button>{status&&<div className={status.startsWith("SUCCESS")?"notice success":"notice"} role="status">{status.startsWith("SUCCESS")?<a href={explorer(status.slice(8))} target="_blank" rel="noreferrer">交易已确认 <ExternalLink/></a>:status}</div>}</div></section><footer><span>Program <code>BsyakU…7ut8c</code></span><span>仅限 devnet · 请勿使用真实资产</span></footer></main>}
