"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import {useConnection,useWallet} from "@solana/wallet-adapter-react";
import {WalletMultiButton} from "@solana/wallet-adapter-react-ui";
import {createAssociatedTokenAccountInstruction,getAssociatedTokenAddressSync} from "@solana/spl-token";
import {ArrowDownUp,ArrowLeft,ExternalLink,RefreshCw} from "lucide-react";
import {PublicKey,Transaction} from "@solana/web3.js";
import {fetchPool,formatTokenAmount,mintDecimals,PoolState,quote,shortAddress,swapIx,tokenAmount,TOKEN_PROGRAM_ID} from "@/lib/amm";

type Side={mint:PublicKey;vault:PublicKey;reserve:bigint;decimals:number};
const txExplorer=(s:string)=>`https://explorer.solana.com/tx/${s}?cluster=devnet`;
const addressExplorer=(s:string)=>`https://explorer.solana.com/address/${s}?cluster=devnet`;

export default function PoolDetail({address}:{address:string}){
  const {connection}=useConnection(),wallet=useWallet();
  const [pool,setPool]=useState<PoolState|null>(null),[sides,setSides]=useState<[Side,Side]|null>(null),[reversed,setReversed]=useState(false),[amount,setAmount]=useState(""),[slippage,setSlippage]=useState("0.5"),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setStatus("");try{const key=new PublicKey(address),next=await fetchPool(connection,key),infos=await connection.getMultipleAccountsInfo([next.vaultA,next.vaultB,next.mintA,next.mintB]);if(infos.some(info=>!info||!info.owner.equals(TOKEN_PROGRAM_ID)))throw new Error("Pool 的 Token 账户无效");setPool(next);setSides([{mint:next.mintA,vault:next.vaultA,reserve:tokenAmount(infos[0]!),decimals:mintDecimals(infos[2]!)},{mint:next.mintB,vault:next.vaultB,reserve:tokenAmount(infos[1]!),decimals:mintDecimals(infos[3]!)}])}catch(e){setStatus(e instanceof Error?e.message:"Pool 加载失败")}finally{setLoading(false)}},[address,connection]);
  useEffect(()=>{void load()},[load]);
  const [source,destination]=useMemo(()=>sides?(reversed?[sides[1],sides[0]]:sides):[null,null],[sides,reversed]);
  const amountBase=useMemo(()=>{if(!source||!/^\d*(\.\d*)?$/.test(amount)||!amount)return 0n;const [whole,fraction=""]=amount.split(".");if(fraction.length>source.decimals)return 0n;return BigInt(whole||"0")*10n**BigInt(source.decimals)+BigInt(fraction.padEnd(source.decimals,"0")||"0")},[amount,source]);
  const estimated=pool&&source&&destination&&amountBase>0n?quote(amountBase,source.reserve,destination.reserve,pool.feeBps):0n;
  const swap=async()=>{if(!wallet.publicKey||!source||!destination||!pool)return setStatus("请先连接钱包");setBusy(true);setStatus("正在模拟交易…");try{if(amountBase<=0n)throw new Error("请输入有效数量");const slip=Number(slippage);if(!Number.isFinite(slip)||slip<0||slip>50)throw new Error("滑点必须在 0–50% 之间");const userSource=getAssociatedTokenAddressSync(source.mint,wallet.publicKey),userDestination=getAssociatedTokenAddressSync(destination.mint,wallet.publicKey),min=estimated*BigInt(Math.floor((100-slip)*100))/10000n,latest=await connection.getLatestBlockhash(),tx=new Transaction();if(!await connection.getAccountInfo(userDestination))tx.add(createAssociatedTokenAccountInstruction(wallet.publicKey,userDestination,wallet.publicKey,destination.mint));tx.add(swapIx(wallet.publicKey,pool.address,userSource,userDestination,source.vault,destination.vault,amountBase,min));tx.feePayer=wallet.publicKey;tx.recentBlockhash=latest.blockhash;const sim=await connection.simulateTransaction(tx);if(sim.value.err)throw new Error(`模拟失败: ${JSON.stringify(sim.value.err)}`);setStatus("模拟成功，等待钱包签名…");const signature=await wallet.sendTransaction(tx,connection);await connection.confirmTransaction({...latest,signature},"confirmed");setAmount("");await load();setStatus(`SUCCESS:${signature}`)}catch(e){setStatus(e instanceof Error?e.message:"交易失败")}finally{setBusy(false)}};
  if(loading)return <main><div className="detail-shell"><div className="pool-skeleton tall"/></div></main>;
  if(!pool||!source||!destination)return <main><div className="detail-shell"><Link href="/" className="back-link"><ArrowLeft aria-hidden="true"/>返回 Pool 列表</Link><div className="empty-state" role="alert"><strong>无法打开 Pool</strong><span>{status}</span><button onClick={()=>void load()}>重试</button></div></div></main>;
  return <main><header><Link className="brand" href="/" aria-label="K-Swap 首页"><span>K</span>SWAP</Link><div className="network"><i/>DEVNET</div><WalletMultiButton/></header><div className="detail-shell"><Link href="/#pools" className="back-link"><ArrowLeft aria-hidden="true"/>返回 Pool 列表</Link><div className="detail-grid"><section className="pool-summary"><p className="eyebrow">POOL DETAIL</p><h1>{shortAddress(pool.mintA)} <em>/</em> {shortAddress(pool.mintB)}</h1><p>两种 Token 由 Pool 链上状态自动识别，报价使用实时 vault 储备。</p><div className="reserve-list">{sides!.map((side,index)=><div key={side.mint.toBase58()}><span>Token {index?"B":"A"} 储备</span><strong>{formatTokenAmount(side.reserve,side.decimals)}</strong><a href={addressExplorer(side.mint.toBase58())} target="_blank" rel="noreferrer">{side.mint.toBase58()} <ExternalLink aria-hidden="true"/></a></div>)}</div><dl className="pool-facts"><div><dt>手续费</dt><dd>{pool.feeBps} bps</dd></div><div><dt>Owner</dt><dd>{shortAddress(pool.owner)}</dd></div><div><dt>Pool PDA</dt><dd>{shortAddress(pool.address)}</dd></div></dl></section><section className="trade-card detail-trade" aria-busy={busy}><div className="swap-title"><div><p className="eyebrow">EXACT-IN</p><h2>Swap</h2></div><button className="icon-button" aria-label="刷新储备" onClick={()=>void load()} disabled={busy}><RefreshCw aria-hidden="true"/></button></div><label>支付 · Token {reversed?"B":"A"}<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.0"/></label><div className="asset-address">{source.mint.toBase58()}</div><button className="flip" aria-label="交换代币方向" onClick={()=>setReversed(value=>!value)}><ArrowDownUp aria-hidden="true"/></button><label>预计收到 · Token {reversed?"A":"B"}<input value={formatTokenAmount(estimated,destination.decimals)} readOnly aria-readonly="true"/></label><div className="asset-address">{destination.mint.toBase58()}</div><label>滑点容忍度（%）<input inputMode="decimal" value={slippage} onChange={e=>setSlippage(e.target.value)}/></label><div className="details"><span>最低收到</span><code>{formatTokenAmount(estimated*BigInt(Math.floor((100-Math.max(0,Math.min(50,Number(slippage)||0)))*100))/10000n,destination.decimals)}</code></div><button className="submit" disabled={busy||!wallet.connected||amountBase<=0n} onClick={()=>void swap()}>{busy?"处理中…":wallet.connected?"预检并交换":"请先连接钱包"}</button>{status&&<div className={status.startsWith("SUCCESS")?"notice success":"notice"} role="status" aria-live="polite">{status.startsWith("SUCCESS")?<a href={txExplorer(status.slice(8))} target="_blank" rel="noreferrer">交易已确认 <ExternalLink aria-hidden="true"/></a>:status}</div>}</section></div></div></main>;
}
